version: "3.7"

services:
  db:
    image: postgres:12.4
    restart: always
    ports:
    - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: psiria/yamdb-final:latest
    restart: always
    volumes:
      - static_value:/code/static/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_value:/var/html/static/
    depends_on:
      - web

volumes:
  postgres_data:
  static_value: